apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090 # 'prometheus' is the service name
    isDefault: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100 # 'loki' is the service name